### ISSUE TITLE
Problem with AMP and pagination

### ISSUE THREAD

**Issue by eighttheme** [Automattic/amp-wp#276]
When i activate AMP plugin my home page pagination stop working (just home page) .
When user clicked on page 2 it does not go to page 2 and just back to home page .
I'm using page as a home page and showing my posts .(sorry for my english.)

**Comment by mjangda** [comment]
There's a known issue with pagination that was fixed in https://github.com/Automattic/amp-wp/commit/21180205487d71e595088e2cd1d1acba3f240ea5

This will go out in the next release.

**Comment by ladislavsulc** [comment]
Hi, I still have this issue on the latest version, also when clicking on "display non-amp version" nothing happens.
